[package]
name = "crawler1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
surf = "2.3.2"
html5ever = "0.26.0"
url = "2.3.1"